#!/usr/bin/env bash

#==============================
# Forked from http://github.com/daneden/dotfiles
#==============================

# First, let's set up some ouput functions
red=$'\e[1;31m'
pur=$'\e[0;35m'
yel=$'\e[0;33m'
grn=$'\e[0;32m'
end=$'\e[0m'

msg() {
  printf "${yel} ~ ${pur}$*${end}\n"
}

suc() {
  printf "${grn}$*${end}\n"
}

warn() {
  printf "${red}$*${end}\n"
}

don() {
  printf "...done\n\n"
}

#==============================
# Introduction
#==============================


#==============================
# Homebrew
# Check presence of Homebrew,
# add bundler, then install our
# desired recipes & update them
#==============================

if [[ `uname` == "Darwin" ]]; then

    printf "Install Homebrew and install bundle? [Y/N]"
    read a

    if [[ $a == "N" || $a == "n" ]]; then
      printf "${pur}Skipped.${end}\n\n"
    else
      printf "\n${grn}Install ...${end}\n\n"

        msg "Installing Homebrew packages..."
        type brew &>/dev/null && printf "`brew bundle`" || echo "`ruby -e \"$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)\" && brew tap Homebrew/bundle && brew bundle`"
        brew update && brew upgrade `brew outdated`
        don

    fi

fi


#==============================
# Dotfiles management
#==============================

msg "Setup dotfiles ..."

set -e

CONFIG="install.conf.json"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"

don

#==============================
#
# OS X Stuff
#
#==============================

printf "Should I apply some predefined OS X settings for you? [Y/N]"
read a

if [[ $a == "N" || $a == "n" ]]; then
  printf "${pur}Okay. I skipped this part.${end}\n\n"
else
  printf "\n${grn}Apply settings ...${end}\n\n"
  sh osx/.osx
fi
