#!/usr/bin/env bash

# Homebrew
printf "Install Homebrew and install bundle? [Y/N]"
read a

if [[ $a == "N" || $a == "n" ]]; then
  printf "Skipped."
else
  printf "Install ...\n\n"

  printf "Installing Homebrew packages..."
  type brew &>/dev/null && printf "`brew bundle`" || echo "`ruby -e \"$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)\" && brew tap Homebrew/bundle && brew bundle`"
  brew update && brew upgrade `brew outdated`
fi

# Dotfiles
printf "Setup dotfiles ..."

set -e

CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"



printf "Done ✅"
