# Taps
tap 'homebrew/bundle'
tap 'homebrew/cask-fonts'
tap 'homebrew/cask'


brew 'bat'
brew 'composer'
brew 'git'
brew 'goaccess'
brew 'htop'
brew 'hub'
brew 'youtube-dl'
brew 'tree'


# brew 'ack'
# brew 'coreutils'
# brew 'grep'
# brew 'ncdu'
# brew 'prettyping'
# brew 'tldr'
# brew 'zsh'
# brew 'zsh-completion'
# brew 'zsh-autosuggestions'


# Development
 brew 'php'
# brew 'mariadb'
 brew 'node'
 brew 'yarn'


# Apps
# cask '1password'
# cask 'alfred'
# cask 'caffeine'
# cask 'dropshare'
# cask 'figma'
# cask 'firefox'
# cask 'google-backup-and-sync'
# cask 'iina'
# cask 'insomnia'
# cask 'istat-menus'
# cask 'iterm2'
# cask 'little-snitch'
# cask 'rescuetime'
# cask 'spotify'
# cask 'sublime-text'
# cask 'tower'
# cask 'transmit'

# Quicklook
# cask 'qlmarkdown'
# cask 'quicklook-json'
# cask 'quicklook-csv'
# cask 'qlstephen'

# Fonts
cask 'font-iosevka'

# Install Mac App Store apps
# mas 'Deliveries', id: 924726344
# mas 'iA Writer', id: 775737590
# mas 'Icon Slate', id: 439697913
# mas 'The Unarchiver', id: 425424353
# mas 'Things', id: 904280696
# mas 'ToothFairy', id: 1191449274
# mas 'Tweetbot', id: 1384080005
